### ISSUE TITLE
Mark Services as Private

### ISSUE THREAD

**Issue by pitchart** [mnapoli/fluent-symfony#12]
According to https://symfony.com/doc/current/service_container/alias_private.html, services can be defined as private :

```yaml
services:
    foo:
        class: Example\Foo
        public: false
```

This package could have something like :

```php
return [
    'foo' => create(Foo::class)
        ->makePrivate(),  // or ->private() but I prefer an action verb in this case
];
```
