### ISSUE TITLE
Support for service deprecation

### ISSUE THREAD

**Issue by pitchart** [mnapoli/fluent-symfony#13]
I'm listing features available in other file configurations.

YAML syntaxe :

```yaml
acme.my_service:
    class: ...
    deprecated: The "%service_id%" service is deprecated since 2.8 and will be removed in 3.0.
```

this package could have :

```php
return [
    'acme.my_service' => create(Foo::class)
        ->deprecate('The "%service_id%" service is deprecated since 2.8 and will be removed in 3.0.'),
];
```
