### ISSUE TITLE
Allow extension configuration -> separate sections?

### ISSUE THREAD

**Issue by mnapoli** [mnapoli/fluent-symfony#2]
Symfony's container separates several sections:

```yaml
imports:
    - ...

framework:
    # ...

parameters:
    # ...

services:
    # ...
```

This package should probably reflect that because currently it's impossible to configure all the extensions (e.g. the `framework`).

Here's an idea:

```php
return [

    'imports' => [
        'config_dev.php',
    ],

    // Define extensions like this
    'framework' => [
    ],

    'parameters' => [
        'foo' => 'bar',
    ],

    'services' => [
        // ....
    ],

];
```

Another possibility:

```php
return [

    imports([
        'config_dev.php',
    ]),

    extension('framework', [
    ]),

    parameters([
        'foo' => 'bar',
    ]),

    services([
        // ....
    ]),

];
```

but that's maybe a bit too weird/too much.
