### ISSUE TITLE
Parent/Child services support

### ISSUE THREAD

**Issue by chalasr** [mnapoli/fluent-symfony#34]
Playing a bit with this, I can't find something about [parent services](http://symfony.com/doc/current/service_container/parent_services.html) i.e. an equivalent for:

```yaml
foo:
    class: App\Foo
    arguments: ['foo', 'bar']

child:
    parent: foo
```

Maybe something like `create($entryId)->parent($parentId)` or just `extend($entryId, $parentId)`?
