### ISSUE TITLE
Abstract services support

### ISSUE THREAD

**Issue by chalasr** [mnapoli/fluent-symfony#35]
Relates to #34. e.g:

```yaml
foo:
    abstract: true
    class: App\FooInterface
    arguments: ['foo', 'bar']

child:
    parent: foo
    class: App\Foo
```

Should not be hard to implement. `create()->abstract()` maybe?
